### ISSUE TITLE
Per-worker instances

### ISSUE THREAD

**Issue by Ale1x** [UnamSanctam/SilentCryptoMiner#1835]
Hi, first of all I thank you for the fantastic project. My question is the following: if a worker is present on one PC, can the same worker be on another PC or will he/she be disconnected? A thousand thanks

I tried with two miner instances with the same worker and one gets disconnected. I wonder if it was my problem or not.

Furthermore, taking a look at the code, I was looking for the function that takes care of taking the environment variables from a configuration file (I assume it is created at build time) but I didn't find any, could you give me some clarification on this?

Thank you so much.

**Comment by UnamSanctam** [comment]
You can have any amount of workers/miner without any disconnects, but on pools they will combine the hashrate of any miners that use the same worker name. So if two of your miners have the same worker name then the pool will show a single worker with those two miners hashrates combined.

The miner does not use configuration files, but instead passes all the arguments as command line arguments (though it's passed through using the PEB ShellInfo to hide the command line options from other programs like Process Hacker or Task Manager):
https://github.com/UnamSanctam/SilentCryptoMiner/blob/ac13f952c19bfce3617aa464f7cb28f4f2a04ca6/SilentCryptoMiner/Forms/Builder.cs#L230
The argstr are the command line arguments.

**Comment by Ale1x** [comment]
Thank you so much for the quick answer.

Again, Keep the project up, really interesting. Big up

**Comment by Ale1x** [comment]
Hi again @UnamSanctam, i'm trying to compile the miner by myself but i'm facing some errors: and I have some questions

1) How can i generate the syscalls file with SysWhispersU? 
2) How can i compile the miner after it (normal g++ compile command?)

Thank you so much!

**Comment by UnamSanctam** [comment]
>How can i generate the syscalls file with SysWhispersU?

You can find the SysWhispersU command here:
https://github.com/UnamSanctam/SilentCryptoMiner/blob/ac13f952c19bfce3617aa464f7cb28f4f2a04ca6/SilentCryptoMiner/Classes/Codedom.cs#L75
SysWhispersU is my own custom version of https://github.com/jthuraisamy/SysWhispers2.

>How can i compile the miner after it (normal g++ compile command?)

The miner build command can be found here:
https://github.com/UnamSanctam/SilentCryptoMiner/blob/ac13f952c19bfce3617aa464f7cb28f4f2a04ca6/SilentCryptoMiner/Forms/Builder.cs#L320

The watchdog build command is here:
https://github.com/UnamSanctam/SilentCryptoMiner/blob/ac13f952c19bfce3617aa464f7cb28f4f2a04ca6/SilentCryptoMiner/Forms/Builder.cs#L283

**Comment by Ale1x** [comment]
Still not able to figure out how to use SysWhispersU.

I got that command from the string: `./syswhispersu.exe -a x64 -l gas --function-prefix "Ut" -f NtSetInformationFile,NtSetInformationProcess,NtCreateFile,NtWriteFile,NtReadFile,NtDeleteFile,NtCreateSection,NtClose,NtMapViewOfSection,NtOpenFile,NtResumeThread,NtGetContextThread,NtSetContextThread,NtAllocateVirtualMemory,NtWriteVirtualMemory,NtFreeVirtualMemory,NtDelayExecution,NtOpenProcess,NtCreateUserProcess,NtOpenProcessToken,NtWaitForSingleObject,NtQueryAttributesFile,NtQueryInformationFile,NtCreateMutant,NtAdjustPrivilegesToken,NtQuerySystemInformation,NtQueryInformationToken,NtOpenKey,NtEnumerateKey,NtQueryValueKey,NtRenameKey -o "UFiles\Syscalls\syscalls"`

But i get thi error: `Traceback (most recent call last):
  File "syswhispers.py", line 960, in <module>
  File "syswhispers.py", line 662, in generate
FileNotFoundError: [Errno 2] No such file or directory: 'UFiles\\Syscalls\\syscalls.c'
[5300] Failed to execute script 'syswhispers' due to unhandled exception!`

**Comment by UnamSanctam** [comment]
Can you try creating the UFiles/Syscalls folder before running the command?

**Comment by Ale1x** [comment]
Nice it worked. Thank you

**Comment by Ale1x** [comment]
Hello again, I apologize for bothering you again.
I'll try to explain my situation better:
I'm trying to compile miner and watchdog individually since I don't need the builder currently. I was able to find the commands to generate the files with SysWhispersU and I was able to find the compile command for the miner. However I have some problems regarding environment variables like $GLOBALRESOURCES etc.

I wanted some advice from you, for private use do you recommend keeping the builder or trying to refactor the code by trying to eliminate it? I hope I have been clear, thank you very much in advance and I apologize for the inconvenience

**Comment by UnamSanctam** [comment]
Well, if you don't want to use the builder then you'll have to find some other way to create the resources and such, for example the whole ReplaceGlobals:
https://github.com/UnamSanctam/SilentCryptoMiner/blob/ac13f952c19bfce3617aa464f7cb28f4f2a04ca6/SilentCryptoMiner/Classes/Codedom.cs#L267
And resource creation:
https://github.com/UnamSanctam/SilentCryptoMiner/blob/ac13f952c19bfce3617aa464f7cb28f4f2a04ca6/SilentCryptoMiner/Classes/Codedom.cs#L234
You will have to do manually before compiling it, and you'll also have to create the assembly resource using windres manually if you haven't already.
You will also have to create the mutex arrays and such and place them into the code if you haven't already.

The builder does a lot of things, so you will have to manually do all those things if you don't want to use the builder.

**Comment by Ale1x** [comment]
Can I write to you privately somewhere? Are you coming to Matrix or Telegram?

Just to ask you a few things regarding my project since I'm not sure if it will be possible with the builder.
