### ISSUE TITLE
Look at this Unam ! !

### ISSUE THREAD

**Issue by error0x1337** [UnamSanctam/SilentCryptoMiner#1932]
hello @UnamSanctam 
i just restarted it and got this error few minutes ago..
![image](https://github.com/UnamSanctam/SilentCryptoMiner/assets/150927220/14139608-69f9-4917-a9ab-9af2ab7377cd)
its only on miners page.

**Comment by error0x1337** [comment]
i didnt even opened anything any time

**Comment by error0x1337** [comment]
![image](https://github.com/UnamSanctam/SilentCryptoMiner/assets/150927220/f95f5c0e-8fe6-4a83-8683-213c79264d32)

**Comment by error0x1337** [comment]
error.log 
"   thrown in /storage/ssd2/878/21383878/public_html/assets/php/templates.php on line 215
[15-Nov-2023 14:15:29 UTC] PHP Fatal error:  Uncaught TypeError: Unsupported operand types: string / int in /storage/ssd2/878/21383878/public_html/assets/php/templates.php:215
Stack trace:
#0 /storage/ssd2/878/21383878/public_html/assets/php/datatables.php(119): unamtTimeFormat()
#1 /storage/ssd2/878/21383878/public_html/class/class.ssp.php(43): {closure}()
#2 /storage/ssd2/878/21383878/public_html/class/class.ssp.php(144): SSP::data_output()
#3 /storage/ssd2/878/21383878/public_html/api/custom-table.php(57): SSP::process()
#4 {main} 
"

**Comment by UnamSanctam** [comment]
Maybe there's something weird in your database.

**Comment by error0x1337** [comment]
> Maybe there's something weird in your database.
but how? never opened it

**Comment by error0x1337** [comment]
it only shows the online miners, while offline miners are not loaded

**Comment by UnamSanctam** [comment]
Either open your database with an SQLite browser and see which entry has an incorrect time (which is what the problem is) or you can simply replace your database with a fresh one.

**Comment by error0x1337** [comment]
Can I move my miners to the another web?

**Comment by error0x1337** [comment]
> Either open your database file with an SQLite browser and see which entry has an incorrect time (which is what the problem is) or you can simply replace your database with a fresh one.

if i replace my db to newer, will i lose my clients?

**Comment by error0x1337** [comment]
i mean if will they still appear on the panel ?

**Comment by UnamSanctam** [comment]
They will reappear when they connect.

**Comment by error0x1337** [comment]
okay ill try reuploading the db, ill download it from your github release

**Comment by error0x1337** [comment]
i reuploaded whole db folder but it throws same alert

**Comment by error0x1337** [comment]
I prefer move miners on another web, How can I do this?

**Comment by UnamSanctam** [comment]
If you have a "Remote Configuration" then you can change the API Endpoint URL to a different one using the `"api-endpoint": "API Endpoint URL"` option though that might not solve the issue, though if you replaced the db folder (specifically the unamwebpanel.db inside it) then it should work already. I'm guessing that some miner is reporting a wrong `run_time` or something, or some person is submitting incorrect data to your web panel.

**Comment by error0x1337** [comment]
> If you have a "Remote Configuration" then you can change the API Endpoint URL to a different one using the `"api-endpoint": "API Endpoint URL"` option though that might not solve the issue, though if you replaced the db folder (specifically the unamwebpanel.db inside it) then it should work already. I'm guessing that some miner is reporting a wrong `run_time` or something, or some person is submitting incorrect data to your web panel.

i think it is fixed now, not throwing the alert anymore

**Comment by error0x1337** [comment]
but now miners GPU doesnt appearing on the panel

**Comment by UnamSanctam** [comment]
They should appear whenever they connect to the web panel, did you change the URL through the "Remote Configuration" or do you use the same old one?

**Comment by error0x1337** [comment]
yh its old one with new database file and some of miner GPUs is not appearing while their CPUs is working fine

**Comment by UnamSanctam** [comment]
Were they there before? Since not all computer can GPU mine.

**Comment by error0x1337** [comment]
yeah they were mining, i think I had something wrong with Miner build setup in 3.3.1 version

**Comment by error0x1337** [comment]
some of miners are appearing on another panel and cant even change them in remobe configuration through panel

**Comment by UnamSanctam** [comment]
Are you trying to change them through a "Remote Configuration" or the web panel configuration?

**Comment by error0x1337** [comment]
from web panel configuration i mean

**Comment by UnamSanctam** [comment]
You must create a "full" configuration if you haven't already (with a pool and wallet and such) for the miner to use it. And the GPU (ethminer) and CPU (xmrig) use 2 different format as well so change both the "Default ethminer" and "Default xmrig" configuration.

**Comment by error0x1337** [comment]
@UnamSanctam i cant change the configuration for some miners through webpanel, why ?

**Comment by error0x1337** [comment]
![image](https://github.com/UnamSanctam/SilentCryptoMiner/assets/150927220/74a23f11-c68b-491b-8bcb-8bf825d9391c)
its mining on hashvault xmr pool.
i apply this 
![image](https://github.com/UnamSanctam/SilentCryptoMiner/assets/150927220/114eeb2c-ecdb-4a1e-ab4e-05f3400c7893)
but its not applied. same problem with another 2 miner

**Comment by UnamSanctam** [comment]
Maybe they aren't able to connect to the 2miners pool. The miner saves up to three different pool configurations in its memory, and if one pool isn't working it tries the next one until one works. They are in this priority:
1) Web panel pool configuration
2) "Remote Configuration" pool configuration
3) Builder pool configuration

**Comment by error0x1337** [comment]
they were connected to 2miners before, since i reupdated the database that happens

**Comment by error0x1337** [comment]
oh, i just checked that miner, and its applied now, weird..

**Comment by UnamSanctam** [comment]
Alright good, the miner contacts the web panel every minute, so a change should be visible on the web panel after about 2 minutes.

**Comment by error0x1337** [comment]
yep ty
